password: 11

server:
  applicationConnectors:
    - type: http
      port: 8085
    - type: https
      port: 8443
      keyStorePath: dropbookmarks.keystore
      keyStorePassword: 11111111
      validateCerts: false

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: 11111111
  url: jdbc:mysql://localhost:3306/wizard_db?useSSL=false