# Use root/example as user/password credentials
version: '3.1'

services:

  mypostgres:
    image: postgres:14.6
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: 11111111
      POSTGRES_USER: user
      POSTGRES_DB: mydb